/*
 * TRANSLATION FILE (FRENCH)
 * 
 * Alternative to stringtable.csv which is simpler to install for the mission maker.
 * The token ""%1"" represents a dynamic value generated by the scripts, like a vehicle name.
 * 
 * Alternative au stringtable.csv qui est plus simple à installer pour le créateur de mission.
 * Le mot-clé ""%1"" représente une valeur dynamique fournie par les scripts, comme par exemple un nom de véhicule.
 */

STR_R3F_LOG_action_heliporter = "Heliporter l'objet";
STR_R3F_LOG_action_heliporter_fait = "Objet ""%1"" accroché.";
STR_R3F_LOG_action_heliport_larguer = "Larguer l'objet";
STR_R3F_LOG_action_heliport_parachute = "Paradrop the object";
STR_R3F_LOG_action_heliport_larguer_fait = "Objet ""%1"" largué.";
STR_R3F_LOG_action_heliport_attente = "Accrochage... (%1)";
STR_R3F_LOG_action_heliport_echec_attente = "Heliportage annulé ! Restez en stationnaire pendant l'accrochage.";

STR_R3F_LOG_action_deplacer_objet = "Prendre ""%1""";
STR_R3F_LOG_action_relacher_objet = "Relâcher ""%1""";
STR_R3F_LOG_action_aligner_pente = "Ajuster à la pente";
STR_R3F_LOG_action_aligner_sol = "Ajuster au sol";
STR_R3F_LOG_action_aligner_horizon = "Ajuster de niveau";
STR_R3F_LOG_action_tourner = "Pivoter (touches X / C)";
STR_R3F_LOG_action_rapprocher = "Rapprocher (touches F / R)";
STR_R3F_LOG_ne_pas_monter_dans_vehicule = "Vous ne pouvez pas monter dans un véhicule tant que vous déplacez cet objet !";
STR_LOCK_OBJECT = "Lock this object";
STR_UNLOCK_OBJECT = "Unlock this object";

STR_R3F_LOG_action_charger_deplace = "Charger dans le véhicule";
STR_R3F_LOG_action_selectionner_objet_charge = "Charger ""%1"" dans...";
STR_R3F_LOG_action_charger_selection = "... charger dans ""%1""";
STR_R3F_LOG_action_selectionner_objet_fait = "Sélectionnez maintenant la destination pour ""%1""...";
STR_R3F_LOG_action_charger_en_cours = "Chargement en cours...";
STR_R3F_LOG_action_charger_fait = "L'objet ""%1"" a été chargé dans ""%2"".";
STR_R3F_LOG_action_charger_pas_assez_de_place = "Il n'y pas assez de place pour cet objet dans ce véhicule !";

STR_R3F_LOG_action_remorquer_direct = "Remorquer ""%1""";
STR_R3F_LOG_action_remorquer_deplace = "Remorquer l'objet";
STR_R3F_LOG_action_detacher = "Décrocher l'objet";
STR_R3F_LOG_action_detacher_fait = "Objet décroché.";
STR_R3F_LOG_action_detacher_impossible_pour_ce_vehicule = "Seul le pilote peut décrocher cet objet.";

STR_R3F_LOG_action_contenu_vehicule = "Voir le contenu du véhicule";
STR_R3F_LOG_action_decharger_en_cours = "Déchargement en cours...";
STR_R3F_LOG_action_decharger_fait = "L'objet ""%1"" a été déchargé du véhicule.";
STR_R3F_LOG_action_decharger_deja_fait = "L'objet a déjà été déchargé !";
STR_R3F_LOG_action_decharger_deplacable_exceptionnel = "Une fois relâché, cet objet ne pourra plus être déplacé manuellement.<br/>Confirmez-vous l'action ?";

STR_R3F_LOG_action_ouvrir_usine = "Ouvrir l'usine de création";
STR_R3F_LOG_action_creer_en_cours = "Création en cours...";
STR_R3F_LOG_action_creer_fait = "L'objet ""%1"" a été créé.";
STR_R3F_LOG_action_creer_pas_assez_credits = "L'usine ne dispose pas assez de crédits pour créer cet objet.";
STR_R3F_LOG_action_revendre_usine_direct = "Renvoyer ""%1"" à l'usine";
STR_R3F_LOG_action_revendre_usine_deplace = "Renvoyer à l'usine";
STR_R3F_LOG_action_revendre_usine_selection = "... renvoyer à l'usine";
STR_R3F_LOG_action_revendre_en_cours = "Renvoi à l'usine en cours...";
STR_R3F_LOG_action_revendre_fait = "L'objet ""%1"" a été renvoyé à l'usine.";
STR_R3F_LOG_action_revendre_decharger_avant = "Vous ne pouvez pas le renvoyer à l'usine tant que sa cargaison n'est pas vide !";

STR_R3F_LOG_mutex_action_en_cours = "L'opération en cours n'est pas terminée !";
STR_R3F_LOG_joueur_dans_objet = "Un joueur se trouve dans l'objet ""%1"" !";
STR_R3F_LOG_objet_en_cours_transport = "L'objet ""%1"" est déjà en cours de transport !";
STR_R3F_LOG_objet_remorque_en_cours = "Impossible car l'objet ""%1"" remorque un autre objet !";
STR_R3F_LOG_trop_loin = "Impossible car l'objet ""%1"" est trop loin !";

STR_R3F_LOG_dlg_CV_titre = "Contenu du véhicule";
STR_R3F_LOG_dlg_CV_capacite_vehicule = "Chargement : %1/%2";
STR_R3F_LOG_dlg_CV_btn_decharger = "DECHARGER";
STR_R3F_LOG_dlg_CV_btn_fermer = "ANNULER";

STR_R3F_LOG_dlg_LO_titre = "Usine de création";
STR_R3F_LOG_dlg_LO_credits_restants = "Crédits restants : %1";
STR_R3F_LOG_dlg_LO_btn_creer = "CREER";
STR_R3F_LOG_dlg_LO_btn_fermer = "ANNULER";

STR_R3F_LOG_nom_fonctionnalite_proprietes = "Propriétés";
STR_R3F_LOG_nom_fonctionnalite_side = "Camp";
STR_R3F_LOG_nom_fonctionnalite_places = "Places assises";
STR_R3F_LOG_nom_fonctionnalite_passif = "Il peut être :";
STR_R3F_LOG_nom_fonctionnalite_passif_deplace = "Déplacé par le joueur";
STR_R3F_LOG_nom_fonctionnalite_passif_heliporte = "Héliporté";
STR_R3F_LOG_nom_fonctionnalite_passif_remorque = "Remorqué";
STR_R3F_LOG_nom_fonctionnalite_passif_transporte = "Transporté";
STR_R3F_LOG_nom_fonctionnalite_passif_transporte_capacite = "coût charg. %1";
STR_R3F_LOG_nom_fonctionnalite_actif = "Il peut :";
STR_R3F_LOG_nom_fonctionnalite_actif_heliporte = "Héliporter";
STR_R3F_LOG_nom_fonctionnalite_actif_remorque = "Remorquer";
STR_R3F_LOG_nom_fonctionnalite_actif_transporte = "Transporter";
STR_R3F_LOG_nom_fonctionnalite_actif_transporte_capacite = "charg. max %1";

STR_R3F_LOG_deverrouillage_en_cours = "Déverrouillage... (%1)";
STR_R3F_LOG_deverrouillage_echec_attente = "Déverrouillage annulé ! Maintenez la visée de l'objet pendant le compte-à-rebours.";
STR_R3F_LOG_deverrouillage_succes_attente = "Objet déverrouillé.";
STR_R3F_LOG_action_deverrouiller = "Déverrouiller ""%1""";
STR_R3F_LOG_action_deverrouiller_impossible = "Objet verrouillé";