/****** TOW WITH VEHICLE  ******/

/**
 * List of class names of (ground or air) vehicles which can tow towables objects.
 */
R3F_LOG_CFG_remorqueurs = [
	"B_APC_Tracked_01_CRV_F",
	"B_APC_Tracked_01_rcws_F",
	"B_APC_Wheeled_01_cannon_F",
	"B_MBT_01_arty_F",
	"B_MBT_01_cannon_F",
	"B_MBT_01_mlrs_F",
	"B_MRAP_01_F",
	"B_MRAP_01_gmg_F",
	"B_MRAP_01_hmg_F",
	"B_Truck_01_ammo_F",
	"B_Truck_01_covered_F",
	"B_Truck_01_Fuel_F",
	"B_Truck_01_medical_F",
	"B_Truck_01_Repair_F",
	"B_Truck_01_transport_F",
	"C_Hatchback_01_F",
	"C_Hatchback_01_sport_F",
	"C_Offroad_01_F",
	"C_SUV_01_F",
	"C_Van_01_box_F",
	"C_Van_01_Fuel_F",
	"C_Van_01_transport_F",
	"I_G_Offroad_01_armed_F",
	"I_G_Offroad_01_F",
	"I_G_Van_01_Fuel_F",
	"I_G_Van_01_transport_F",
	"I_MRAP_03_F",
	"I_MRAP_03_gmg_F",
	"I_MRAP_03_hmg_F",
	"I_Truck_02_ammo_F",
	"I_Truck_02_box_F",
	"I_Truck_02_covered_F",
	"I_Truck_02_Fuel_F",
	"I_Truck_02_medical_F",
	"I_Truck_02_transport_F",
	"O_APC_Tracked_02_cannon_F",
	"O_APC_Wheeled_02_rcws_F",
	"O_MBT_02_arty_F",
	"O_MBT_02_cannon_F",
	"O_MRAP_02_F",
	"O_MRAP_02_gmg_F",
	"O_MRAP_02_hmg_F",
	"O_Truck_02_Ammo_F",
	"O_Truck_02_box_F",
	"O_Truck_02_covered_F",
	"O_Truck_02_Fuel_F",
	"O_Truck_02_medical_F",
	"O_Truck_02_transport_F"
];

/**
 * List of class names of towables objects.
 */
R3F_LOG_CFG_objets_remorquables = [
	"B_APC_Wheeled_01_cannon_F",
	"B_MRAP_01_F",
	"B_MRAP_01_gmg_F",
	"B_MRAP_01_hmg_F",
	"C_Hatchback_01_F",
	"C_Hatchback_01_sport_F",
	"C_Offroad_01_F",
	"C_SUV_01_F",
	"C_Van_01_box_F",
	"C_Van_01_Fuel_F",
	"C_Van_01_transport_F",
	"I_G_Offroad_01_armed_F",
	"I_G_Offroad_01_F",
	"I_G_Van_01_Fuel_F",
	"I_G_Van_01_transport_F",
	"I_MRAP_03_F",
	"I_MRAP_03_gmg_F",
	"I_MRAP_03_hmg_F",
	"I_Truck_02_ammo_F",
	"I_Truck_02_box_F",
	"I_Truck_02_covered_F",
	"I_Truck_02_Fuel_F",
	"I_Truck_02_medical_F",
	"I_Truck_02_transport_F",
	"O_APC_Wheeled_02_rcws_F",
	"O_MRAP_02_F",
	"O_MRAP_02_gmg_F",
	"O_MRAP_02_hmg_F",
	"O_Truck_02_Ammo_F",
	"O_Truck_02_box_F",
	"O_Truck_02_covered_F",
	"O_Truck_02_Fuel_F",
	"O_Truck_02_medical_F",
	"O_Truck_02_transport_F"
];

/****** LIFT WITH VEHICLE  ******/

/**
 * List of class names of air vehicles which can lift liftables objects.
 */
R3F_LOG_CFG_heliporteurs = [
	"B_Heli_Attack_01_F",
	"B_Heli_Light_01_armed_F",
	"B_Heli_Light_01_F",
	"B_Heli_Transport_01_camo_F",
	"B_Heli_Transport_01_F",
	"I_Heli_Transport_02_F",
	"O_Heli_Attack_02_black_F",
	"O_Heli_Attack_02_F",
	"O_Heli_Light_02_F",
	"O_Heli_Light_02_unarmed_F"
];

/**
 * List of class names of liftables objects.
 * Liste des noms de classes des objets h�liportables.
 */
R3F_LOG_CFG_objets_heliportables = [
	"B_APC_Wheeled_01_cannon_F",
	"B_MRAP_01_F",
	"B_MRAP_01_gmg_F",
	"B_MRAP_01_hmg_F",
	"C_Hatchback_01_F",
	"C_Hatchback_01_sport_F",
	"C_Offroad_01_F",
	"C_SUV_01_F",
	"C_Van_01_box_F",
	"C_Van_01_Fuel_F",
	"C_Van_01_transport_F",
	"I_G_Offroad_01_armed_F",
	"I_G_Offroad_01_F",
	"I_G_Van_01_Fuel_F",
	"I_G_Van_01_transport_F",
	"I_MRAP_03_F",
	"I_MRAP_03_gmg_F",
	"I_MRAP_03_hmg_F",
	"I_Truck_02_ammo_F",
	"I_Truck_02_box_F",
	"I_Truck_02_covered_F",
	"I_Truck_02_Fuel_F",
	"I_Truck_02_medical_F",
	"I_Truck_02_transport_F",
	"O_APC_Wheeled_02_rcws_F",
	"O_MRAP_02_F",
	"O_MRAP_02_gmg_F",
	"O_MRAP_02_hmg_F",
	"O_Truck_02_Ammo_F",
	"O_Truck_02_box_F",
	"O_Truck_02_covered_F",
	"O_Truck_02_Fuel_F",
	"O_Truck_02_medical_F",
	"O_Truck_02_transport_F"
];


/****** LOAD IN VEHICLE / CHARGER DANS LE VEHICULE ******/


R3F_LOG_CFG_transporteurs = [
	["B_APC_Tracked_01_CRV_F", 10],
	["B_APC_Tracked_01_rcws_F", 10],
	["B_APC_Wheeled_01_cannon_F", 10],
	["B_APC_Wheeled_01_cannon_F",10],
	["B_Boat_Armed_01_minigun_F", 10],
	["B_Boat_Transport_01_F", 10],
	["B_Heli_Attack_01_F", 10],
	["B_Heli_Light_01_armed_F", 10],
	["B_Heli_Light_01_F", 10],
	["B_Heli_Transport_01_camo_F", 20],
	["B_Heli_Transport_01_F", 20],
	["B_MBT_01_arty_F", 10],
	["B_MBT_01_cannon_F", 10],
	["B_MBT_01_mlrs_F", 10],
	["B_MRAP_01_F", 25],
	["B_MRAP_01_gmg_F", 25],
	["B_MRAP_01_hmg_F", 25],
	["B_Quadbike_01_F", 5],
	["B_Truck_01_ammo_F", 90],
	["B_Truck_01_covered_F", 90],
	["B_Truck_01_Fuel_F", 90],
	["B_Truck_01_medical_F", 90],
	["B_Truck_01_Repair_F", 90],
	["B_Truck_01_transport_F", 90],
	["C_Boat_Civil_01_F", 10],
	["C_Boat_Civil_01_police_F", 10],
	["C_Boat_Civil_01_rescue_F", 10],
	["C_Hatchback_01_F", 20],
	["C_Hatchback_01_sport_F", 20],
	["C_Offroad_01_F", 30],
	["C_Quadbike_01_F", 5],
	["C_SUV_01_F", 25],
	["C_Van_01_box_F", 40],
	["C_Van_01_Fuel_F", 35],
	["C_Van_01_transport_F", 40],
	["I_Boat_Armed_01_minigun_F", 10],
	["I_Boat_Transport_01_F", 10],
	["I_G_Boat_Transport_01_F", 10],
	["I_G_Offroad_01_armed_F", 15],
	["I_G_Offroad_01_F", 30],
	["I_G_Quadbike_01_F", 5],
	["I_G_Van_01_Fuel_F", 35],
	["I_G_Van_01_transport_F", 40],
	["I_Heli_Transport_02_F", 20],
	["I_MRAP_03_F",25],
	["I_MRAP_03_gmg_F",25],
	["I_MRAP_03_hmg_F",25],
	["I_Quadbike_01_F", 5],
	["I_Truck_02_ammo_F", 50],
	["I_Truck_02_box_F", 50],
	["I_Truck_02_covered_F", 50],
	["I_Truck_02_Fuel_F", 50],
	["I_Truck_02_medical_F", 50],
	["I_Truck_02_transport_F", 50],
	["O_APC_Tracked_02_cannon_F", 10],
	["O_APC_Wheeled_02_rcws_F", 10],
	["O_APC_Wheeled_02_rcws_F",10],
	["O_Boat_Armed_01_hmg_F", 10],
	["O_Boat_Transport_01_F", 10],
	["O_Heli_Attack_02_F", 10],
	["O_Heli_Light_02_F", 20],
	["O_Heli_Light_02_unarmed_F", 20],
	["O_MBT_02_arty_F", 10],
	["O_MBT_02_cannon_F", 10],
	["O_MRAP_02_F", 25],
	["O_MRAP_02_gmg_F", 25],
	["O_MRAP_02_hmg_F", 25],
	["O_Quadbike_01_F", 5],
	["O_Truck_02_Ammo_F", 50],
	["O_Truck_02_box_F", 50],
	["O_Truck_02_covered_F", 50],
	["O_Truck_02_Fuel_F", 50],
	["O_Truck_02_medical_F", 50],
	["O_Truck_02_transport_F", 50]
];

 
R3F_LOG_CFG_objets_transportables =  [
	["B_Quadbike_01_F", 10],
	["Box_East_Support_F", 5],
	["Box_East_Wps_F", 5],
	["Box_East_WpsSpecial_F", 5],
	["Box_NATO_Support_F", 5],
	["Box_NATO_Wps_F", 5],
	["Box_NATO_WpsSpecial_F", 5],
	["C_Quadbike_01_F", 10],
	["I_G_Quadbike_01_F", 10],
	["I_Quadbike_01_F", 10],
	["Land_BagBunker_Large_F", 10],
	["Land_BagBunker_Small_F", 5],
	["Land_BagBunker_Tower_F", 7],
	["Land_BagFence_Long_F", 3],
	["Land_BarGate_F", 3],
	["Land_Canal_Wall_Stairs_F", 3],
	["Land_Canal_WallSmall_10m_F", 4],
	["Land_CargoBox_V1_F", 5],
	["Land_CncBarrierMedium4_F", 4],
	["Land_CncShelter_F", 4],
	["Land_CncWall4_F", 5],
	["Land_HBarrier_1_F", 1],
	["Land_HBarrier_3_F", 3],
	["Land_HBarrier_5_F", 5],
	["Land_HBarrierBig_F", 5],
	["Land_HBarrierTower_F", 8],
	["Land_HBarrierWall4_F", 4],
	["Land_HBarrierWall4_F", 4],
	["Land_HBarrierWall6_F", 5],
	["Land_HBarrierWall6_F", 6],
	["Land_LampShabby_F",3],
	["Land_MetalBarrel_F", 2],
	["Land_Mil_ConcreteWall_F", 5],
	["Land_Mil_WallBig_4m_F", 5],
	["Land_Obstacle_Ramp_F", 5],
	["Land_Pipes_large_F", 5],
	["Land_RampConcrete_F", 5],
	["Land_RampConcreteHigh_F", 6],
	["Land_Sacks_goods_F", 2],
	["Land_Scaffolding_F", 3],
	["Land_Shoot_House_Wall_F", 3],
	["Land_Stone_8m_F", 5],
	["Land_ToiletBox_F", 6],
	["Land_WaterBarrel_F", 2],
	["O_Quadbike_01_F", 10]
];

/****** MOVABLE-BY-PLAYER OBJECTS / OBJETS DEPLACABLES PAR LE JOUEUR ******/

R3F_LOG_CFG_objets_deplacables = [
	"B_Boat_Transport_01_F",
	"B_Lifeboat",
	"B_Quadbike_01_F",
	"Box_East_Support_F",
	"Box_East_Wps_F",
	"Box_East_WpsSpecial_F",
	"Box_NATO_Support_F",
	"Box_NATO_Wps_F",
	"Box_NATO_WpsSpecial_F",
	"C_Quadbike_01_F",
	"C_Rubberboat",
	"I_Boat_Transport_01_F",
	"I_G_Quadbike_01_F",
	"I_Quadbike_01_F",
	"Land_BagBunker_Large_F",
	"Land_BagBunker_Small_F",
	"Land_BagBunker_Tower_F",
	"Land_BagFence_Long_F",
	"Land_BarGate_F",
	"Land_Canal_Wall_Stairs_F",
	"Land_Canal_WallSmall_10m_F",
	"Land_CncBarrierMedium4_F",
	"Land_CncShelter_F",
	"Land_CncWall4_F",
	"Land_HBarrier_1_F",
	"Land_HBarrier_3_F",
	"Land_HBarrier_5_F",
	"Land_HBarrierBig_F",
	"Land_HBarrierTower_F",
	"Land_HBarrierWall4_F",
	"Land_HBarrierWall4_F",
	"Land_HBarrierWall6_F",
	"Land_HBarrierWall6_F",
	"Land_LampDecor_F",
	"Land_LampShabby_F",
	"Land_MetalBarrel_F",
	"Land_Mil_ConcreteWall_F",
	"Land_Mil_WallBig_4m_F",
	"Land_Pipes_large_F",
	"Land_RampConcrete_F",
	"Land_RampConcreteHigh_F",
	"Land_Sacks_goods_F",
	"Land_Scaffolding_F",
	"Land_Shoot_House_Wall_F",
	"Land_Stone_8m_F",
	"Land_ToiletBox_F",
	"Land_WaterBarrel_F",
	"O_Boat_Transport_01_F",
	"O_Lifeboat",
	"O_Quadbike_01_F"
];
