//	@file Version: 1.0
//	@file Name: addMilCap.sqf
//	@file Author: AgentRev
//	@file Created: 21/10/2013 18:40
//	@file Args:

if (!isServer) exitWith {};

private ["_unit", "_time"];

_unit = _this;
_time = time;

// BIS_randomSeed2 is generated by \Civil\scripts\randomize_civ1.sqf in characters_f.pbo
waitUntil {sleep 0.1; _unit getVariable ["BIS_randomSeed2", 0] >= 2 || {headgear _unit != ""} || {time - _time >= 3}};

if (leader _unit == _unit) then
{
	_unit addHeadgear "H_MilCap_blue";
}
else
{
	_unit addHeadgear "H_MilCap_mcamo";
};
